### ISSUE TITLE
Multi person DMs

### ISSUE THREAD

**Issue by keith** [rawdigits/wee-slack#133]
Not sure when this feature got rolled out (or if it's still in testing), but in a multi person DM the buffer is named `#mpdm-nick1--nick2--nick3-1`. We should probably clean this up somehow, but I'm not sure what the expected buffer name should be. In Slack.app it says `Nick1, Nick2` (where nick3 above was me).

I'm happy to take a stab at this as this feature is rolled out.

**Comment by rawdigits** [comment]
We had a chat about this in the freenode channel. considering either of these:

%name1,name2,name3
&name1,name2,name3

**Comment by keith** [comment]
Is there a need for the leading symbols?

**Comment by keith** [comment]
Just going to throw this in here, we might also want to fold after a certain point. I was in an mpdm with 7 people which makes buffers.pl huge:

<img width="634" alt="screen shot 2015-12-10 at 0 08 46" src="https://cloud.githubusercontent.com/assets/283886/11710253/a067ec6c-9ed2-11e5-9457-8662b678b18b.png">

**Comment by tfheen** [comment]
Not sure how to fold it usefully though, if you're in a dm with the same people but one.. Need some thought on how to represent this well, I think.

**Comment by keith** [comment]
I wonder if we should have a max length and then use a `...` like suffix to differentiate.

**Comment by adamgibbins** [comment]
I'm not sure this is the right place for it - but I also note Weechat counts these as channels, rather than query windows - so doesn't notify on messages.  That's kind of annoying, I keep finding they get lost in a bunch of channels.  It'd be good if that behaviour could be changed somehow, I'd expect everything in these windows to be treated as a highlight notification (as they are on Slack).

**Comment by keith** [comment]
I thought that actually wasn't how this worked in Slack.app? I had to change my notification settings to make them act like DMs. Has this been changed on their side?
