### ISSUE TITLE
make this work with screen_away.py

### ISSUE THREAD

**Issue by rawdigits** [rawdigits/wee-slack#161]
sets you away when you detach a screen session (and hopefully tmux)

need to make sure /away global works in slack

**Comment by furai** [comment]
Thanks for looking into this.

**Comment by torhve** [comment]
I recently implemented this in matrix.lua. Maybe this patch could serve as inspiration.

https://github.com/torhve/weechat-matrix-protocol-script/commit/87596c43377719c60d7041827e71cfa6f726af32

WeeChat also recently switch its bar item away to be in core instead of irc plugin, so away status is actually displayed in the input bar on non-irc-buffers too.
