### ISSUE TITLE
Closing the server buffer should close all channel buffers

### ISSUE THREAD

**Issue by jeaye** [rawdigits/wee-slack#43]
When I `/close` the server buffer, weechat should disconnect and all channel buffers should be closed. This is how it works normally in weechat. In wee-slack, closing the server buffer does nothing other than close the server buffer. This means I manually have to `/close` all wee-slack buffers when I want to disconnect?

**Comment by rawdigits** [comment]
Because of how slack synchronizes channels, this is a bit tricky. It is probably worth supporting some kind of disconnect that does this but I never really log out of my slack groups, so low priority for me. Happy to take a pull request that does this.

Important note: if someone creates one, it should **NOT** do `/close` on each buffer, which would result in the user leaving every channel they are a member of.

**Comment by rawdigits** [comment]
There hasn't been a PR for this, and I'm not particularly interested in adding this myself. If some people +1 this in the future I'll take another look, but closing for now.
